load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
      ":attributes",
      ":syscalls",
      ":fuse",
      ":dir_cache_fs",
      "@absl//absl/cleanup",
      "@absl//absl/flags:flag",
      "@absl//absl/flags:parse",
      "@absl//absl/flags:usage",
      "@absl//absl/log",
      "@absl//absl/log:flags",
      "@absl//absl/log:initialize",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
      "@libfuse//:libfuse",
    ],
)

cc_library(
    name = "sqlite",
    srcs = ["sqlite.cc"],
    hdrs = ["sqlite.h"],
    deps = [
      ":attributes",
      ":ret_check",
      ":status",
      "@absl//absl/cleanup",
      "@absl//absl/log",
      "@absl//absl/log:check",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@sqlite//:sqlite3",
    ],
)

cc_library(
    name = "status",
    hdrs = ["status.h"],
    srcs = [
      "status.cc",
      "errno.cc",
    ],
    deps = [
      "@absl//absl/container:flat_hash_map",
      "@absl//absl/log",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
      "@absl//absl/strings:cord",
    ],
)

cc_library(
    name = "syscalls",
    hdrs = [
      "syscalls.h",
      "fd.h",
    ],
    srcs = [
      "syscalls.cc",
      "fd.cc",
    ],
    deps = [
      ":attributes",
      ":ret_check",
      ":status",
      "@absl//absl/container:flat_hash_map",
      "@absl//absl/log",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
    ],
)

cc_library(
    name = "fuse",
    hdrs = ["fuse.h"],
    srcs = ["fuse.cc"],
    deps = [
      ":attributes",
      ":syscalls",
      ":status",
      "@absl//absl/status:statusor",
      "@absl//absl/status",
      "@absl//absl/log",
      "@absl//absl/time",
      "@absl//absl/log:check",
      "@absl//absl/container:flat_hash_set",
      "@absl//absl/strings:str_format",
      "@libfuse//:libfuse",
    ],
)

cc_library(
    name = "attributes",
    hdrs = ["attributes.h"],
)

cc_library(
    name = "device_id",
    srcs = ["device_id.cc"],
    hdrs = ["device_id.h"],
    deps = [
      ":status",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
      "@absl//absl/strings:str_format",
    ],
)

cc_test(
    name = "device_id_test",
    size = "small",
    srcs = ["device_id_test.cc"],
    deps = [
      ":device_id",
      ":status",
      "@absl//absl/hash",
      "@absl//absl/status",
      "@absl//absl/status:status_matchers",
      "@absl//absl/status:statusor",
      "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "mount_fds",
    srcs = ["mount_fds.cc"],
    hdrs = ["mount_fds.h"],
    deps = [
      ":device_id",
      ":syscalls",
      "@absl//absl/container:flat_hash_map",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
    ],
)

cc_test(
    name = "mount_fds_test",
    size = "small",
    srcs = ["mount_fds_test.cc"],
    deps = [
      ":device_id",
      ":mount_fds",
      ":syscalls",
      "@absl//absl/status",
      "@absl//absl/status:status_matchers",
      "@absl//absl/status:statusor",
      "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "dir_cache_fs",
    srcs = ["dir_cache_fs.cc"],
    hdrs = ["dir_cache_fs.h"],
    deps = [
      ":attributes",
      ":fuse",
      ":status",
      ":syscalls",
      "@absl//absl/log",
      "@absl//absl/log:check",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@libfuse//:libfuse",
    ],
)

cc_library(
    name = "ret_check",
    hdrs = ["ret_check.h"],
    deps = [
      "@absl//absl/status",
    ],
)

cc_library(
    name = "memory",
    hdrs = ["memory.h"],
)

cc_test(
    name = "smoke_test",
    size = "small",
    srcs = ["smoke_test.cc"],
    deps = ["@googletest//:gtest_main"],
)

cc_test(
    name = "libfuse_version_test",
    size = "small",
    srcs = ["libfuse_version_test.cc"],
    deps = [
      "@googletest//:gtest_main",
      "@libfuse//:libfuse",
    ],
)
