cc_library(
    name = "status",
    hdrs = ["status.h"],
    srcs = ["status.cc"],
    deps = [
      "@absl//absl/log",
      "@absl//absl/status",
      "@absl//absl/strings",
      "@absl//absl/strings:cord",
    ],
)

cc_library(
    name = "syscalls",
    hdrs = [
      "syscalls.h",
      "fd.h",
      "mount.h",
    ],
    srcs = [
      "syscalls.cc",
      "fd.cc",
      "mount.cc",
    ],
    deps = [
      "@absl//absl/log",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/strings",
    ],
)

cc_library(
    name = "fuse",
    hdrs = ["fuse.h"],
    srcs = ["fuse.cc"],
    deps = [
      ":syscalls",
      ":status",
      "@absl//absl/status:statusor",
      "@absl//absl/status",
      "@absl//absl/log:check",
      "@absl//absl/log",
      "@absl//absl/container:flat_hash_set",
      "@absl//absl/strings:str_format",
      "@fuse//:fuse",
    ],
)

cc_library(
    name = "io_uring",
    hdrs = ["io_uring.h"],
    srcs = ["io_uring.cc"],
    deps = [
      "@absl//absl/status:statusor",
      "@absl//absl/status",
      "@uring//:uring",
    ],
)

cc_library(
    name = "sqlite",
    srcs = ["sqlite.cc"],
    hdrs = ["sqlite.h"],
    deps = [
      ":status",
      "@absl//absl/status",
      "@absl//absl/status:statusor",
      "@absl//absl/log",
      "@absl//absl/log:check",
      "@sqlite//:sqlite3",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
      ":io_uring",
      ":syscalls",
      ":fuse",
      ":status",
      ":sqlite",
      "@absl//absl/flags:flag",
      "@absl//absl/status",
      "@absl//absl/log",
      "@absl//absl/log:initialize",
      "@absl//absl/log:flags",
      "@absl//absl/flags:parse",
      "@absl//absl/flags:usage",
      "@sqlite//:sqlite3",
    ],
)

cc_binary(
    name = "mkfs",
    srcs = ["mkfs.cc"],
    deps = [
      ":status",
      ":sqlite",
      "@absl//absl/flags:flag",
      "@absl//absl/status",
      "@absl//absl/log",
      "@absl//absl/time",
      "@absl//absl/log:initialize",
      "@absl//absl/log:flags",
      "@absl//absl/flags:parse",
      "@absl//absl/flags:usage",
      "@sqlite//:sqlite3",
    ],
)
