------------------------ MODULE readdirplus_unlocked ------------------------
(***************************************************************************)
(* Known bug: formal/ finding readdirplus_unlocked (found by this model,  *)
(* fixed in plan step R4). Readdirplus could leave out a name made        *)
(* unknown after its completeness check.                                  *)
(*                                                                         *)
(* DirCacheFS::Readdirplus called EnsureListed (IsDirComplete: complete   *)
(* and no unknown row), then replied "." with EntryFor(dir), which        *)
(* refreshes the directory's attributes with syscalls if they are         *)
(* unknown, then ParentOf (syscalls if the directory's own dentry is      *)
(* unknown), and only then cache::ListDir, which yields the present rows  *)
(* and skips every other state. A name that became unknown in between (a  *)
(* mutation's phase 1) was left out although it might exist. Readdir had  *)
(* the same shape for a non-root directory (ParentOf). Unreachable        *)
(* through dcfs's own mutations while the kernel holds the directory's    *)
(* lock across READDIRPLUS and every namespace mutation of it; real with  *)
(* requests on coroutines without that lock (this configuration), or for  *)
(* a name made unknown without the lock (an invalidation, not modelled).  *)
(* Fixed by DirCacheFS::ListCached: the listing is taken right after the  *)
(* check, before any syscall.                                             *)
(*                                                                         *)
(* Re-introduced by BugReaddirplusUnlocked (the listing is taken after    *)
(* "."'s refresh, without checking again). Expected:                      *)
(* ServedFromCacheIsCurrent is violated.                                  *)
(***************************************************************************)
EXTENDS MC
=============================================================================
