------------------------ MODULE rename_stale_source ------------------------
(***************************************************************************)
(* Known bug: formal/ finding rename_stale_source (found by this model,   *)
(* fixed in plan step R4). Rename's phase 3 could link the new name to a  *)
(* stale object.                                                          *)
(*                                                                         *)
(* DirCacheFS::Rename resolved the source (and destination) with          *)
(* LookupOrPopulate before phase 1, and phase 3 linked newname to that    *)
(* resolved id if the mutation Owns(newparent). Owns only notices         *)
(* mutations that overlap from phase 1 on. If the resolve was answered    *)
(* from a probe or listing that was not recorded (a concurrent mutation   *)
(* of the parent made CanFill fail), the id could be stale by phase 1:    *)
(* another rename replaced the name meanwhile and ended. renameat2 then   *)
(* moved the new object, and phase 3 recorded the old one. (In the code,  *)
(* LinkDentry failed, and the transaction rolled back, if the old         *)
(* object's row was gone; it was kept when the object had another link,   *)
(* so the wrong entry was recorded.) Unreachable while the kernel holds   *)
(* the parent's lock across a RENAME and every other namespace operation  *)
(* of it; real with two renames of one directory in flight at once        *)
(* (coroutines without that lock: this configuration). Fixed by           *)
(* cache::BeginRename's `resolved` snapshot: phase 1 verifies that no     *)
(* mutation of the inodes the rename names began or ended since before    *)
(* the resolve, and none is in flight, else Rename resolves again.        *)
(*                                                                         *)
(* Re-introduced by BugRenameStaleSource (phase 1 does not verify).       *)
(* Expected: CacheNeverWrong is violated.                                 *)
(***************************************************************************)
EXTENDS MC
=============================================================================
