---------------------------- MODULE crash_litmus ----------------------------
(***************************************************************************)
(* What the backing filesystem's crash consistency leaves to the caller    *)
(* (step 12.8): Ferrite's litmus tests (MClitmus.tla) whose surprising     *)
(* outcome is reachable. dcfs adds no crash outcome (CrashRefines), and    *)
(* it adds no atomicity or durability beyond its own sync points either;   *)
(* each configuration here expects the counterexample:                     *)
(*                                                                         *)
(*  - litmus_replace_metaprefix, litmus_replace_ext4: atomic replace via   *)
(*    rename (ARVR). Create t, write it, rename it over f, with no fsync   *)
(*    before the rename: a power loss may keep the rename and lose t's     *)
(*    data, and dcfs then serves f empty, as the backing filesystem has    *)
(*    it (LitmusOK). The specifications allow it (DFSCQ's metadata-prefix, *)
(*    Ferrite's Definition 7, which the paper relates to the "ext4 data    *)
(*    loss" of 2009); whether ext4 data=ordered with auto_da_alloc can     *)
(*    still produce it is doubtful. Only the sequential regime forbids it  *)
(*    (MC_litmus_replace_seq.cfg).                                         *)
(*  - litmus_create_metaprefix, litmus_create_ext4: atomic create via      *)
(*    rename (ACVR): the same, f new.                                      *)
(*  - litmus_fsync_file_direct_ext4: implied directory fsync, with the     *)
(*    program's own barrier only (SyncBarrier <- FsyncOnly, the program    *)
(*    as on the backing filesystem directly): Ferrite's Definition 7       *)
(*    orders before an fsync of f only the updates of f, and the create of *)
(*    f is an update of D, so after the fsync returned a power loss may    *)
(*    leave no f (LitmusBackingOK). (Real ext4 commits its whole journal   *)
(*    transaction at an fsync, the create with it; the regime is the       *)
(*    paper's specification, which allows more.) Through dcfs it holds:    *)
(*    the sync point after FSYNC runs syncfs (MC_litmus_fsync_file_ext4).  *)
(*  - litmus_fsync_dir_direct_ext4, litmus_fsync_dir_direct_metaprefix:    *)
(*    directory fsync with D's fsync only, DirFsyncPersistsFiles = FALSE:  *)
(*    f is there after the fsync returned, but empty (LitmusBackingOK).    *)
(*    Step 11.2's ACE tests found this of ext4 (fault_ace.sh: "an fsync of *)
(*    the directory alone is not a persistence point for file data").      *)
(*    Through dcfs it holds (MC_litmus_fsync_dir_ext4); with the switch    *)
(*    TRUE it holds directly too (MC_litmus_fsync_dir_direct_files_ext4).  *)
(***************************************************************************)
EXTENDS MClitmus
=============================================================================
