---------------------------- MODULE ident_limits ----------------------------
(***************************************************************************)
(* What the identity model (ident.tla) shows does not hold, each a         *)
(* documented limitation stated as a checked one (each configuration here  *)
(* expects its counterexample):                                            *)
(*                                                                         *)
(*  - ident_wipe: today's identity, a cache wipe: an NFS handle of an      *)
(*    object that still exists gets ESTALE (the new database knows no row  *)
(*    for its nodeid, or one with another generation). README's            *)
(*    "NFS handles do not survive deleting the cache database"; Phase 14   *)
(*    lifts it (MC_ident_target.cfg).                                      *)
(*  - ident_power_loss: today's identity, a power loss: rows recorded      *)
(*    since the last durable commit (a phase 1, a WAL checkpoint, a start) *)
(*    are lost with their nodeids, and so are the handles of their objects *)
(*    (ESTALE, never another object: the reissued id gets a fresh random   *)
(*    generation). Phase 14 lifts it.                                      *)
(*  - ident_no_generations: a filesystem whose handles carry no generation *)
(*    and which reports neither FS_IOC_GETVERSION nor a birth time: after  *)
(*    a power loss, the start's probe of a recovered row of a freed object *)
(*    reaches the object that recycled its inode number and keeps the row *)
(*    for it (ReuseDetected). README's "Generation 0 objects"; dcfs        *)
(*    assumes handles that encode the generation (docs/design.md,          *)
(*    "Assumptions"), and Phase 14 refuses other filesystems.              *)
(*  - ident_target_out_of_band: Phase 14's identity with a recycling       *)
(*    behind dcfs's back: the kernel holds inode number 1 with the old     *)
(*    generation, a lookup of the new object replies inode number 1 with   *)
(*    the new one, and fuse_iget marks the old inode bad (EIO, not ESTALE; *)
(*    NoBadInode). Today's identity gives the new object a new nodeid      *)
(*    (MC_ident_oob.cfg). Phase 14's plan: "Out-of-band recycling stays    *)
(*    unsupported".                                                        *)
(*  - ident_target_uncached_nodeid: Phase 14's identity, also out of band: *)
(*    a request on a nodeid the kernel holds finds the row stale (ESTALE,  *)
(*    the row goes); the next request finds no row and, as the plan has    *)
(*    it ("any request for an uncached nodeid resolves through 14.2"),     *)
(*    opens the inode by number and reaches the object that recycled it    *)
(*    (HeldResolvesToItsObject). Only LOOKUP(nodeid, ".") has the kernel   *)
(*    compare generations; other requests carry no generation, so Phase 14 *)
(*    must compare with the generation it handed out in this mount, or     *)
(*    answer ESTALE.                                                       *)
(***************************************************************************)
EXTENDS MCident
=============================================================================
