-------------------------- MODULE reval_out_of_band --------------------------
(***************************************************************************)
(* What dcfs's exclusive-access rule buys (docs/design.md, "Assumptions"): *)
(* with changes behind dcfs's back (OutOfBand), the revalidation model     *)
(* (reval.tla) checks that the flags part still holds (MC_reval_oob.cfg), *)
(* and each configuration here expects the counterexample that shows what  *)
(* does not, a documented limitation stated as a checked one:             *)
(*                                                                         *)
(*  - out_of_band_mode: a chmod a-w made directly on the backing file is   *)
(*    not seen. The kernel's cached attributes (until their timeout) and   *)
(*    dcfs's cached mode (until something invalidates it) still say        *)
(*    writable, the kernel's default_permissions check reads them, and a   *)
(*    writable open the backing filesystem would refuse is granted         *)
(*    (OpenModeNeverGrantsMore). dcfs opens the backing file as root, so   *)
(*    its own open does not refuse it either.                              *)
(*  - out_of_band_casefold: chattr +F made directly on an empty directory  *)
(*    is not seen; a name created through dcfs afterwards ("a") leaves the *)
(*    cached negative entry of its other case ("A") answering absent,      *)
(*    while the backing directory finds "a" (DirCacheNeverWrong).          *)
(*  - out_of_band_stale: after an out-of-band change, nothing has to      *)
(*    revalidate the cached record, so it may stay wrong forever           *)
(*    (CachedDecisionsConverge, liveness, without the symmetry).           *)
(***************************************************************************)
EXTENDS MCreval
=============================================================================
