"""tla_trace_test: trace validation of a QEMU guest run (formal/README.md).

Boots a guest whose dcfs records its protocol events (a qemu_cc_test's
initramfs whose test installs dcfs/testonly's recorder, or the traced e2e
initramfs, //test/qemu:initramfs_traced, running a guest script), then runs
formal/trace_validate.sh: it collects the traces from the serial log and
checks each with TLC against formal/Trace.tla. TLC runs on the host on the
pinned JDK; the guest under the pinned QEMU and kernel, exactly as
qemu_test/qemu_cc_test run them (test/qemu/scripts/run-qemu.sh).
"""

load("@rules_java//java/common:java_common.bzl", "java_common")

def _tla_trace_test_impl(ctx):
    runtime = ctx.attr._jdk[java_common.JavaRuntimeInfo]
    script = ctx.actions.declare_file(ctx.label.name + ".sh")

    def sp(f):
        return f.short_path

    qemu_args = []
    if ctx.attr.unit:
        qemu_args.append("--unit")
    qemu_args += [
        "--mke2fs",
        sp(ctx.file._mke2fs),
        "--mke2fs-conf",
        sp(ctx.file._mke2fs_conf),
        "--mkfs-xfs",
        sp(ctx.file._mkfs_xfs),
        "--mkfs-btrfs",
        sp(ctx.file._mkfs_btrfs),
        "--qemu",
        sp(ctx.file._qemu),
        "--qboot",
        sp(ctx.file._qboot),
        sp(ctx.file._kernel),
        sp(ctx.file.initramfs),
    ]
    if not ctx.attr.unit:
        if not ctx.attr.guest_script:
            fail("tla_trace_test(%s): guest_script is required unless unit = True" % ctx.label.name)
        qemu_args.append(ctx.attr.guest_script)
    qemu_args += ctx.attr.disks

    classpath = ":".join([
        "$PWD/" + sp(ctx.file._overrides),
        "$PWD/" + sp(ctx.file._jar),
        "$PWD/" + sp(ctx.file._community_modules),
    ])
    spec_dir = ctx.file._trace_tla.short_path.rsplit("/", 1)[0]

    expect = []
    if ctx.attr.expect_reject:
        expect = ["--expect-reject", ctx.attr.expect_reject, ctx.attr.expect_reject_event]

    def q(s):
        return "'" + s.replace("'", "'\\''") + "'"

    ctx.actions.write(
        output = script,
        is_executable = True,
        content = "\n".join([
            "#!/bin/bash",
            "# Generated by //formal:trace.bzl (tla_trace_test).",
            "set -euo pipefail",
            "exec \"$PWD/{validate}\" --java \"$PWD/{java}\" --cp \"{cp}\" --spec-dir \"$PWD/{spec}\" --lock {lock} {expect} -- \"$PWD/{run_qemu}\" {args}".format(
                validate = sp(ctx.file._validate),
                java = runtime.java_executable_runfiles_path,
                cp = classpath,
                spec = spec_dir,
                lock = "true" if ctx.attr.lock else "false",
                expect = " ".join([q(x) for x in expect]),
                run_qemu = sp(ctx.file._run_qemu),
                args = " ".join([q(a) for a in qemu_args]),
            ),
            "",
        ]),
    )

    files = [
        ctx.file._validate,
        ctx.file._run_qemu,
        ctx.file.initramfs,
        ctx.file._kernel,
        ctx.file._qemu,
        ctx.file._qboot,
        ctx.file._mke2fs,
        ctx.file._mke2fs_conf,
        ctx.file._mkfs_xfs,
        ctx.file._mkfs_btrfs,
        ctx.file._overrides,
        ctx.file._jar,
        ctx.file._community_modules,
        ctx.file._trace_tla,
        ctx.file._trace_cfg,
        ctx.file._dcfs_tla,
    ]
    runfiles = ctx.runfiles(files = files, transitive_files = runtime.files)
    for dep in [ctx.attr._qemu, ctx.attr._mke2fs, ctx.attr._mkfs_xfs, ctx.attr._mkfs_btrfs]:
        runfiles = runfiles.merge(dep[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = script, runfiles = runfiles)]

_tla_trace_test = rule(
    implementation = _tla_trace_test_impl,
    test = True,
    doc = "Runs a recording guest and validates every trace it produced " +
          "against formal/Trace.tla (see formal/trace_validate.sh).",
    attrs = {
        "initramfs": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The guest initramfs: a qemu_cc_test's <name>.cpio.gz " +
                  "(unit = True), or //test/qemu:initramfs_traced.",
        ),
        "unit": attr.bool(
            doc = "A qemu_cc_test's initramfs (run-qemu.sh --unit).",
        ),
        "guest_script": attr.string(
            doc = "For an e2e initramfs: the guest/*.sh script to run.",
        ),
        "disks": attr.string_list(
            doc = "Disk specs for run-qemu.sh, e.g. \"vdb:ext4:320M\".",
        ),
        "lock": attr.bool(
            doc = "Whether the run kept the kernel's directory lock (the " +
                  "model's KernelDirLock): true for a guest's real " +
                  "requests, false for the forged-request harness.",
        ),
        "expect_reject": attr.string(
            doc = "The fault-injection test: the trace " +
                  "(<trace name>@<directory inode>) that must be rejected.",
        ),
        "expect_reject_event": attr.string(
            doc = "An extended regular expression the first event the " +
                  "model cannot explain must match.",
        ),
        "_validate": attr.label(
            default = "//formal:trace_validate.sh",
            allow_single_file = True,
        ),
        "_trace_tla": attr.label(default = "//formal:Trace.tla", allow_single_file = True),
        "_trace_cfg": attr.label(default = "//formal:Trace.cfg", allow_single_file = True),
        "_dcfs_tla": attr.label(default = "//formal:dcfs.tla", allow_single_file = True),
        "_run_qemu": attr.label(
            default = "//test/qemu:scripts/run-qemu.sh",
            allow_single_file = True,
        ),
        "_kernel": attr.label(
            default = "//third_party/linux:bzImage",
            allow_single_file = True,
        ),
        "_qemu": attr.label(
            default = "//third_party/qemu:qemu_system_x86_64",
            allow_single_file = True,
        ),
        "_qboot": attr.label(
            default = "@qemu//:pc-bios/qboot.rom",
            allow_single_file = True,
        ),
        "_mke2fs": attr.label(
            default = "//third_party/e2fsprogs:mke2fs",
            allow_single_file = True,
        ),
        "_mke2fs_conf": attr.label(
            default = "//third_party/e2fsprogs:mke2fs.conf",
            allow_single_file = True,
        ),
        "_mkfs_xfs": attr.label(
            default = "//third_party/xfsprogs:mkfs_xfs",
            allow_single_file = True,
        ),
        "_mkfs_btrfs": attr.label(
            default = "//third_party/btrfs-progs:mkfs_btrfs",
            allow_single_file = True,
        ),
        "_overrides": attr.label(
            default = "//third_party/tlaplus:tlc_overrides",
            allow_single_file = True,
        ),
        "_jar": attr.label(
            default = "@tla2tools//file",
            allow_single_file = True,
        ),
        "_community_modules": attr.label(
            default = "@tla_community_modules//file",
            allow_single_file = True,
        ),
        "_jdk": attr.label(
            default = "@remotejdk21_linux//:jdk",
            providers = [java_common.JavaRuntimeInfo],
        ),
    },
)

def tla_trace_test(name, tags = [], **kwargs):
    """Declares a trace validation test (see _tla_trace_test's attributes).

    It boots a QEMU guest, so it carries qemu_test's tags (KVM, no sandbox,
    the guest's resources) on top of `tags`.
    """
    _tla_trace_test(
        name = name,
        tags = ["e2e", "no-sandbox", "requires-kvm", "cpu:2", "resources:memory:1200"] + tags,
        **kwargs
    )
