"""tla_trace_test: trace validation of a QEMU guest run (formal/README.md).

Boots a guest whose dcfs records its protocol events (a qemu_cc_test's
initramfs whose test installs dcfs/testonly's recorder, or the traced e2e
initramfs, //test/qemu:initramfs_traced, running a guest script), then runs
formal/trace_validate.sh: it collects the traces from the serial log and
checks each with TLC against formal/Trace.tla. TLC runs on the host on the
pinned JDK; the guest under the pinned QEMU and kernel, exactly as
qemu_test/qemu_cc_test run them (test/qemu/scripts/run-qemu.sh).
"""

load("@rules_java//java/common:java_common.bzl", "java_common")
load("//test/qemu:qemu_cc_test.bzl", "UNIT_ASAN_MEM", "UNIT_MEM")
load("//test/qemu:qemu_test.bzl", "E2E_ASAN_MEM", "E2E_MEM", "QEMU_OVERHEAD_MB", "mem_args_for", "resolve_mem")

def _tla_trace_test_impl(ctx):
    runtime = ctx.attr._jdk[java_common.JavaRuntimeInfo]
    script = ctx.actions.declare_file(ctx.label.name + ".sh")

    def sp(f):
        return f.short_path

    qemu_args = []
    if ctx.attr.unit:
        qemu_args.append("--unit")
    qemu_args += ctx.attr.mem_args
    qemu_args += [
        "--mke2fs",
        sp(ctx.file._mke2fs),
        "--mke2fs-conf",
        sp(ctx.file._mke2fs_conf),
        "--mkfs-xfs",
        sp(ctx.file._mkfs_xfs),
        "--mkfs-btrfs",
        sp(ctx.file._mkfs_btrfs),
        "--qemu",
        sp(ctx.file._qemu),
        "--qboot",
        sp(ctx.file._qboot),
        sp(ctx.file._kernel),
        sp(ctx.file.initramfs),
    ]
    if not ctx.attr.unit:
        if not ctx.attr.guest_script:
            fail("tla_trace_test(%s): guest_script is required unless unit = True" % ctx.label.name)
        qemu_args.append(ctx.attr.guest_script)
    qemu_args += ctx.attr.disks

    classpath = ":".join([
        "$PWD/" + sp(ctx.file._overrides),
        "$PWD/" + sp(ctx.file._jar),
        "$PWD/" + sp(ctx.file._community_modules),
    ])
    spec_dir = ctx.file._trace_tla.short_path.rsplit("/", 1)[0]

    expect = []
    if ctx.attr.allow_cuts:
        expect += ["--allow-cuts", ",".join(ctx.attr.allow_cuts)]
    if ctx.attr.root:
        expect += ["--root", ctx.attr.root, "--root-cuts", ",".join(ctx.attr.root_cuts)]
    if ctx.attr.expect_reject:
        expect += ["--expect-reject", ctx.attr.expect_reject, ctx.attr.expect_reject_event]

    def q(s):
        return "'" + s.replace("'", "'\\''") + "'"

    ctx.actions.write(
        output = script,
        is_executable = True,
        content = "\n".join([
            "#!/bin/bash",
            "# Generated by //formal:trace.bzl (tla_trace_test).",
            "set -euo pipefail",
            "exec \"$PWD/{validate}\" --java \"$PWD/{java}\" --cp \"{cp}\" --spec-dir \"$PWD/{spec}\" --lock {lock} {expect} -- \"$PWD/{run_qemu}\" {args}".format(
                validate = sp(ctx.file._validate),
                java = runtime.java_executable_runfiles_path,
                cp = classpath,
                spec = spec_dir,
                lock = "true" if ctx.attr.lock else "false",
                expect = " ".join([q(x) for x in expect]),
                run_qemu = sp(ctx.file._run_qemu),
                args = " ".join([q(a) for a in qemu_args]),
            ),
            "",
        ]),
    )

    files = [
        ctx.file._validate,
        ctx.file._run_qemu,
        ctx.file.initramfs,
        ctx.file._kernel,
        ctx.file._qemu,
        ctx.file._qboot,
        ctx.file._mke2fs,
        ctx.file._mke2fs_conf,
        ctx.file._mkfs_xfs,
        ctx.file._mkfs_btrfs,
        ctx.file._overrides,
        ctx.file._jar,
        ctx.file._community_modules,
        ctx.file._trace_tla,
        ctx.file._trace_cfg,
        ctx.file._dcfs_tla,
    ]
    runfiles = ctx.runfiles(files = files, transitive_files = runtime.files)
    for dep in [ctx.attr._qemu, ctx.attr._mke2fs, ctx.attr._mkfs_xfs, ctx.attr._mkfs_btrfs]:
        runfiles = runfiles.merge(dep[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = script, runfiles = runfiles)]

_tla_trace_test = rule(
    implementation = _tla_trace_test_impl,
    test = True,
    doc = "Runs a recording guest and validates every trace it produced " +
          "against formal/Trace.tla (see formal/trace_validate.sh).",
    attrs = {
        "initramfs": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The guest initramfs: a qemu_cc_test's <name>.cpio.gz " +
                  "(unit = True), or //test/qemu:initramfs_traced.",
        ),
        "unit": attr.bool(
            doc = "A qemu_cc_test's initramfs (run-qemu.sh --unit).",
        ),
        "mem_args": attr.string_list(
            doc = "run-qemu.sh's --mem flag; set by tla_trace_test from " +
                  "its mem/asan_mem (a select() on the sanitizer builds).",
        ),
        "guest_script": attr.string(
            doc = "For an e2e initramfs: the guest/*.sh script to run.",
        ),
        "disks": attr.string_list(
            doc = "Disk specs for run-qemu.sh, e.g. \"vdb:ext4:320M\".",
        ),
        "lock": attr.bool(
            doc = "Whether the run kept the kernel's directory lock (the " +
                  "model's KernelDirLock): true for a guest's real " +
                  "requests, false for the forged-request harness.",
        ),
        "allow_cuts": attr.string_list(
            doc = "The categories of cut (a step the model does not have; " +
                  "see dcfs/testonly/trace_recorder.h) a trace of this run " +
                  "may end at. Any other cut fails the test.",
        ),
        "root": attr.string(
            doc = "A trace (<trace name>@<directory inode>) that must be " +
                  "valid and reach the end of the run, or a cut in root_cuts.",
        ),
        "root_cuts": attr.string_list(
            doc = "The cut categories `root` may end at (default: none).",
        ),
        "expect_reject": attr.string(
            doc = "The fault-injection test: the trace " +
                  "(<trace name>@<directory inode>) that must be rejected.",
        ),
        "expect_reject_event": attr.string(
            doc = "An extended regular expression the first event the " +
                  "model cannot explain must match.",
        ),
        "_validate": attr.label(
            default = "//formal:trace_validate.sh",
            allow_single_file = True,
        ),
        "_trace_tla": attr.label(default = "//formal:Trace.tla", allow_single_file = True),
        "_trace_cfg": attr.label(default = "//formal:Trace.cfg", allow_single_file = True),
        "_dcfs_tla": attr.label(default = "//formal:dcfs.tla", allow_single_file = True),
        "_run_qemu": attr.label(
            default = "//test/qemu:scripts/run-qemu.sh",
            allow_single_file = True,
        ),
        "_kernel": attr.label(
            default = "//third_party/linux:bzImage",
            allow_single_file = True,
        ),
        "_qemu": attr.label(
            default = "//third_party/qemu:qemu_system_x86_64",
            allow_single_file = True,
        ),
        "_qboot": attr.label(
            default = "@qemu//:pc-bios/qboot.rom",
            allow_single_file = True,
        ),
        "_mke2fs": attr.label(
            default = "//third_party/e2fsprogs:mke2fs",
            allow_single_file = True,
        ),
        "_mke2fs_conf": attr.label(
            default = "//third_party/e2fsprogs:mke2fs.conf",
            allow_single_file = True,
        ),
        "_mkfs_xfs": attr.label(
            default = "//third_party/xfsprogs:mkfs_xfs",
            allow_single_file = True,
        ),
        "_mkfs_btrfs": attr.label(
            default = "//third_party/btrfs-progs:mkfs_btrfs",
            allow_single_file = True,
        ),
        "_overrides": attr.label(
            default = "//third_party/tlaplus:tlc_overrides",
            allow_single_file = True,
        ),
        "_jar": attr.label(
            default = "@tla2tools//file",
            allow_single_file = True,
        ),
        "_community_modules": attr.label(
            default = "@tla_community_modules//file",
            allow_single_file = True,
        ),
        "_jdk": attr.label(
            default = "@remotejdk21_linux//:jdk",
            providers = [java_common.JavaRuntimeInfo],
        ),
    },
)

def tla_trace_test(name, tags = [], mem = None, asan_mem = None, **kwargs):
    """Declares a trace validation test (see _tla_trace_test's attributes).

    It boots a QEMU guest, so it carries qemu_test's tags (KVM, no sandbox,
    the guest's resources) on top of `tags`, and takes the same guest memory
    allowances (test/qemu/qemu_test.bzl; the unit or e2e defaults).
    """
    unit = kwargs.get("unit", False)
    mem, asan_mem = resolve_mem(
        mem,
        asan_mem,
        UNIT_MEM if unit else E2E_MEM,
        UNIT_ASAN_MEM if unit else E2E_ASAN_MEM,
    )
    _tla_trace_test(
        name = name,
        mem_args = mem_args_for(mem, asan_mem),
        tags = ["e2e", "no-sandbox", "requires-kvm", "cpu:2", "resources:memory:%d" % (mem + QEMU_OVERHEAD_MB)] + tags,
        **kwargs
    )

def _tla_trace_log_test_impl(ctx):
    runtime = ctx.attr._jdk[java_common.JavaRuntimeInfo]
    script = ctx.actions.declare_file(ctx.label.name + ".sh")

    def sp(f):
        return f.short_path

    def q(s):
        return "'" + s.replace("'", "'\\''") + "'"

    args = ["--lock", "true" if ctx.attr.lock else "false"]
    if ctx.attr.expect_reject:
        args += ["--expect-reject", ctx.attr.expect_reject, ctx.attr.expect_reject_event]
    if ctx.attr.root:
        args += ["--root", ctx.attr.root, "--root-cuts", ",".join(ctx.attr.root_cuts)]
    classpath = ":".join([
        "$PWD/" + sp(ctx.file._overrides),
        "$PWD/" + sp(ctx.file._jar),
        "$PWD/" + sp(ctx.file._community_modules),
    ])
    validate = "\"$PWD/{validate}\" --java \"$PWD/{java}\" --cp \"{cp}\" --spec-dir \"$PWD/{spec}\" {args} --log \"$PWD/{log}\"".format(
        validate = sp(ctx.file._validate),
        java = runtime.java_executable_runfiles_path,
        cp = classpath,
        spec = ctx.file._trace_tla.short_path.rsplit("/", 1)[0],
        args = " ".join([q(a) for a in args]),
        log = sp(ctx.file.log),
    )
    if ctx.attr.expect_validator_failure:
        # The validator itself must fail, saying why (a check of the
        # validator's own rules, e.g. the root check).
        body = [
            "status=0",
            validate + " >\"$TEST_TMPDIR/validate.out\" 2>&1 || status=$?",
            "cat \"$TEST_TMPDIR/validate.out\"",
            "if [[ \"$status\" -eq 0 ]]; then echo \"FAIL: the validator passed\"; exit 1; fi",
            "if ! grep -Eq -- {ere} \"$TEST_TMPDIR/validate.out\"; then echo \"FAIL: the validator failed, but not with: \"{ere}; exit 1; fi".format(ere = q(ctx.attr.expect_validator_failure)),
            "echo \"PASS: the validator failed as expected\"",
        ]
    else:
        body = ["exec " + validate]
    ctx.actions.write(
        output = script,
        is_executable = True,
        content = "\n".join([
            "#!/bin/bash",
            "# Generated by //formal:trace.bzl (tla_trace_log_test).",
            "set -euo pipefail",
        ] + body + [""]),
    )
    files = [
        ctx.file._validate,
        ctx.file.log,
        ctx.file._overrides,
        ctx.file._jar,
        ctx.file._community_modules,
        ctx.file._trace_tla,
        ctx.file._trace_cfg,
        ctx.file._dcfs_tla,
    ]
    return [DefaultInfo(
        executable = script,
        runfiles = ctx.runfiles(files = files, transitive_files = runtime.files),
    )]

tla_trace_log_test = rule(
    implementation = _tla_trace_log_test_impl,
    test = True,
    doc = "Checks the traces in a file of trace lines against Trace.tla " +
          "(no guest): for testing Trace.tla on hand-written traces.",
    attrs = {
        "log": attr.label(allow_single_file = True, mandatory = True),
        "lock": attr.bool(),
        "expect_reject": attr.string(),
        "expect_reject_event": attr.string(),
        "root": attr.string(doc = "As tla_trace_test's root."),
        "root_cuts": attr.string_list(doc = "As tla_trace_test's root_cuts."),
        "expect_validator_failure": attr.string(
            doc = "An extended regular expression: the validator must fail " +
                  "and its output match it (a test of the validator's rules).",
        ),
        "_validate": attr.label(default = "//formal:trace_validate.sh", allow_single_file = True),
        "_trace_tla": attr.label(default = "//formal:Trace.tla", allow_single_file = True),
        "_trace_cfg": attr.label(default = "//formal:Trace.cfg", allow_single_file = True),
        "_dcfs_tla": attr.label(default = "//formal:dcfs.tla", allow_single_file = True),
        "_overrides": attr.label(default = "//third_party/tlaplus:tlc_overrides", allow_single_file = True),
        "_jar": attr.label(default = "@tla2tools//file", allow_single_file = True),
        "_community_modules": attr.label(default = "@tla_community_modules//file", allow_single_file = True),
        "_jdk": attr.label(
            default = "@remotejdk21_linux//:jdk",
            providers = [java_common.JavaRuntimeInfo],
        ),
    },
)
