------------------------- MODULE lifetime_findings --------------------------
(***************************************************************************)
(* Gaps the lifetime model found in the code (README.md, "Findings of the  *)
(* lifetime model"). Each configuration findings/lifetime_*.cfg checks     *)
(* this module and must fail as described there; fixing the code moves the *)
(* configuration into the real model.                                      *)
(*                                                                         *)
(* lifetime_stub_nodeid_reused (OutOfBand): a stub's nodeid is the next up *)
(* from the highest live stub's (cache::SetRefused), so once the highest   *)
(* stub goes (its name stops being refused: a relisting after an out-of-   *)
(* band change) the next refused name gets its nodeid again, which the     *)
(* kernel may still hold for the old one. NodeidStable: refuse m1 (stub    *)
(* 11); look it up; m1's stub goes; refuse m2: stub 11 again, which the    *)
(* kernel holds for m1 (a GETATTR of it is answered with m2's stub until   *)
(* the kernel's next lookup tells the two apart by generation).            *)
(*                                                                         *)
(* lifetime_crash_before_settle: a crash between an unlink's backing       *)
(* syscall and its phase 3 leaves the row of an object that has no name    *)
(* left, with its nlink column not 0, so the start's sweep keeps it: a row *)
(* of a freed object, which nothing deletes until something reaches it by  *)
(* handle. RowsNameLiveObjects: unlink a (no lookup held); crash; start.   *)
(*                                                                         *)
(* lifetime_destroy_with_open_files (DestroyWithOpens): DESTROY with a     *)
(* file still open (SIGTERM, or a lazy unmount: libfuse aborts the         *)
(* connection) and a clean shutdown; the next start is clean, so it does   *)
(* not sweep, and the row of an O_TMPFILE file (or of an unlinked file     *)
(* that was open) stays. UnnamedRowsSwept: TMPFILE; DESTROY; start.        *)
(***************************************************************************)
EXTENDS MClifetime
=============================================================================
