------------------------- MODULE lifetime_findings --------------------------
(***************************************************************************)
(* Gaps the lifetime model found in the code (README.md, "Findings of the  *)
(* lifetime model"). Each configuration findings/lifetime_*.cfg checks     *)
(* this module and must fail as described there; fixing the code moves the *)
(* configuration into the real model.                                      *)
(*                                                                         *)
(* lifetime_destroy_with_open_files (DestroyWithOpens): DESTROY with a     *)
(* file still open (SIGTERM, or a lazy unmount: libfuse aborts the         *)
(* connection). FinishRun records a clean shutdown when no writable open   *)
(* is left (a writable open keeps its row durably dirty, so a TMPFILE      *)
(* still open for writing makes the next start unclean, and its row is     *)
(* swept); after a clean one the start does not sweep, so the row of an    *)
(* unlinked file that was open only for reading (nlink 0 since its phase   *)
(* 3), or of an O_TMPFILE file reopened read-only after its writable       *)
(* descriptor closed, stays, its object freed. UnnamedRowsSwept: look a    *)
(* up; open it read-only; unlink it (phase 3 keeps the row, nlink 0);      *)
(* DESTROY; the start (clean, no sweep).                                   *)
(***************************************************************************)
EXTENDS MClifetime
=============================================================================
