------------------- MODULE lifetime_crash_during_probe -------------------
(***************************************************************************)
(* A gap in the code found by step 12.6 (recovery idempotence, FSCQ's      *)
(* crash condition for recovery): the start's probe of the recovered rows  *)
(* (ProbeRecoveredRows, step 12.4b) works from a list in memory. StartRun  *)
(* reads the dirty set (ListDirty), RecoverDirty empties it, and StartRun's *)
(* kSync commit makes that durable before Startup probes the listed rows   *)
(* (it needs the mount fds). A crash during the probe loses the rows not   *)
(* yet probed: the next start finds the dirty set empty, the clean flag    *)
(* unset, and nothing to probe, so the row of an object a cut removal      *)
(* freed stays (lifetime_crash_before_settle's gap again, one crash        *)
(* later). Identity stays safe (the row's handle is stale: a request gets  *)
(* ESTALE and the row goes), but the row is never swept.                   *)
(*                                                                         *)
(* RecoveryIdempotent (lifetime.tla) is the invariant the fix must make    *)
(* hold: every row still to be probed is still in the dirty set (e.g.      *)
(* StartRun keeps the listed rows dirty until probed, or until the next    *)
(* sync point). This configuration expects its consequence: with two       *)
(* crashes, RowsNameLiveObjects is violated: unlink a (nothing held), a    *)
(* crash before its phase 3, the start lists a's row and empties the dirty *)
(* set, a crash before the probe, the next start probes nothing: a's row   *)
(* names a freed object.                                                   *)
(***************************************************************************)
EXTENDS MClifetime
=============================================================================
