------------------------- MODULE lifetime_findings --------------------------
(***************************************************************************)
(* Gaps the lifetime model found in the code (README.md, "Findings of the  *)
(* lifetime model"). Each configuration findings/lifetime_*.cfg checks     *)
(* this module and must fail as described there; fixing the code moves the *)
(* configuration into the real model.                                      *)
(*                                                                         *)
(* lifetime_stub_nodeid_reused (OutOfBand): a stub's nodeid is the next up *)
(* from the highest live stub's (cache::SetRefused, MAX(id) + 1), so once  *)
(* the highest stub goes the next refused name gets its nodeid again,      *)
(* which the kernel may still hold for the old one. Stubs go on any out-   *)
(* of-band change detected in their parent: ReconcileAttrs relists the     *)
(* directory, ForgetNegativeDentries deletes every refused dentry there    *)
(* and the trigger their stubs; the relisting then mints them again in     *)
(* listing order, so two boundaries can swap nodeids. The kernel's next    *)
(* revalidation finds the same nodeid with a different generation and      *)
(* marks its old inode bad (EIO, not the ESTALE docs/design.md "Boundary   *)
(* stubs" promises); until then a GETATTR (or a LOOKUP of "..") from the   *)
(* old holder is answered with the other stub. NFS handles are safe (the   *)
(* generation is compared). metadata_cache_test.cc's                       *)
(* StubsLiveWithTheirRefusals asserts the reuse on purpose: the fix's      *)
(* failing-first is that assertion flipped. NodeidStable: refuse m1 (stub  *)
(* 11); look it up; m1's stub goes; refuse m2: stub 11 again, which the    *)
(* kernel holds for m1.                                                    *)
(*                                                                         *)
(* lifetime_crash_before_settle: a crash between an unlink's backing       *)
(* syscall and its phase 3 leaves the row of an object that has no name    *)
(* left, with its nlink column not 0, so the start's sweep keeps it: a row *)
(* of a freed object, which nothing deletes until something reaches it by  *)
(* handle. RowsNameLiveObjects: unlink a (no lookup held); crash; start.   *)
(*                                                                         *)
(* lifetime_destroy_with_open_files (DestroyWithOpens): DESTROY with a     *)
(* file still open (SIGTERM, or a lazy unmount: libfuse aborts the         *)
(* connection). FinishRun records a clean shutdown when no writable open   *)
(* is left (a writable open keeps its row durably dirty, so a TMPFILE      *)
(* still open for writing makes the next start unclean, and its row is     *)
(* swept); after a clean one the start does not sweep, so the row of an    *)
(* unlinked file that was open only for reading (nlink 0 since its phase   *)
(* 3), or of an O_TMPFILE file reopened read-only after its writable       *)
(* descriptor closed, stays, its object freed. UnnamedRowsSwept: look a    *)
(* up; open it read-only; unlink it (phase 3 keeps the row, nlink 0);      *)
(* DESTROY; the start (clean, no sweep).                                   *)
(***************************************************************************)
EXTENDS MClifetime
=============================================================================
