------------------------ MODULE readdirplus_unlocked ------------------------
(***************************************************************************)
(* Gap in today's code (found by this model; not fixed): Readdirplus can  *)
(* leave out a name made unknown after its completeness check.            *)
(*                                                                         *)
(* DirCacheFS::Readdirplus calls EnsureListed (IsDirComplete: complete    *)
(* and no unknown row), then replies "." with EntryFor(dir), which        *)
(* refreshes the directory's attributes with syscalls if they are         *)
(* unknown, then ParentOf (syscalls if the directory's own dentry is      *)
(* unknown), and only then cache::ListDir, which yields the present rows  *)
(* and skips every other state. A name that became unknown in between     *)
(* (a mutation's phase 1) is silently left out although it may exist.     *)
(* Readdir has the same shape for a non-root directory (ParentOf).        *)
(*                                                                         *)
(* Unreachable through dcfs's own mutations today: the kernel holds the   *)
(* directory's lock across a READDIRPLUS and every namespace mutation of  *)
(* it (KernelDirLock = TRUE in the real configurations). It needs either  *)
(* requests on several threads or coroutines without that lock, or a      *)
(* name made unknown without the directory's lock (an invalidation        *)
(* through the schema's inodes_delete_unknowns trigger, which this model  *)
(* does not include). The fix: check IsDirComplete again (or list) after  *)
(* the last suspension point.                                             *)
(*                                                                         *)
(* Expected: ServedFromCacheIsCurrent is violated.                        *)
(***************************************************************************)
EXTENDS MC
=============================================================================
