------------------------ MODULE rename_stale_source ------------------------
(***************************************************************************)
(* Gap in today's code (found by this model; not fixed): Rename's phase 3 *)
(* can link the new name to a stale object.                               *)
(*                                                                         *)
(* DirCacheFS::Rename resolves the source (and destination) with          *)
(* LookupOrPopulate before phase 1, and phase 3 links newname to that     *)
(* resolved id if the mutation Owns(newparent). Owns only notices         *)
(* mutations that overlap from phase 1 on. If the resolve was answered    *)
(* from a probe or listing that was not recorded (a concurrent mutation   *)
(* of the parent made CanFill fail), the id can already be stale when     *)
(* phase 1 runs: another rename replaced the name meanwhile and ended.    *)
(* renameat2 then moves the new object, and phase 3 records the old one.  *)
(* (In the code, LinkDentry fails, and the transaction rolls back, if the *)
(* old object's row was deleted; it is kept when the object has another   *)
(* link, so the wrong entry is recorded.)                                 *)
(*                                                                         *)
(* Unreachable today: the kernel holds the parent's lock across the whole *)
(* RENAME, and every other namespace operation of the parent needs it     *)
(* (KernelDirLock = TRUE in the real configurations). It needs two        *)
(* renames of one directory in flight at once (coroutines without that    *)
(* lock). The fix: take the overlap check from before the resolve (a fill *)
(* snapshot), or re-probe the destination after renameat2 as              *)
(* RecordNewChild does for a create.                                      *)
(*                                                                         *)
(* Expected: CacheNeverWrong is violated.                                 *)
(***************************************************************************)
EXTENDS MC
=============================================================================
