------------------------ MODULE sync_during_mutation ------------------------
(***************************************************************************)
(* Gap in today's code (found by this model; not fixed): a sync point     *)
(* that runs while a mutation is between phase 1 and phase 3 can lose the *)
(* mutation's dirty row.                                                  *)
(*                                                                         *)
(* backing::SyncBacking is syncfs(2) on every mount fd, then              *)
(* cache::ClearDirty, which empties the dirty set except inodes with a    *)
(* writable open. It keeps no inode with a mutation in flight. If a       *)
(* mutation's phase 1 commits before the syncfs and its backing syscall   *)
(* runs after it, ClearDirty removes the dirty row of a change that is    *)
(* not durable yet; phase 3 then records it, and a power loss that keeps  *)
(* phase 3 (a later kSync commit or a WAL writeback) and loses the        *)
(* syscall leaves the cache ahead of the backing filesystem with nothing  *)
(* for recovery to forget.                                                *)
(*                                                                         *)
(* Unreachable today: dcfs serves one request at a time, so a sync point  *)
(* (DirCacheFS::MaybeSyncBacking at the start of a request, after an      *)
(* FSYNC/FSYNCDIR, or FinishRun) never overlaps a mutation. The real      *)
(* configurations model that with SyncExclusive = TRUE. Under coroutines  *)
(* ClearDirty must also keep every inode in FillGuards::inflight (or the  *)
(* sync point must wait for in-flight mutations).                         *)
(*                                                                         *)
(* Expected: CrashSafe is violated.                                       *)
(***************************************************************************)
EXTENDS MC
=============================================================================
